spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviereviews
    username: moviereviews
    password: moviereviews
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: 8080

# springdoc OpenAPI UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
